# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.2'

gem 'rake'
gem 'puma'
gem 'rack-ougai'
gem 'rack-request-id'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'

gem 'i18n'
gem 'config'
gem 'amazing_print'

gem 'bunny'

gem 'pg'
gem 'sequel'
gem 'sequel-seed'
gem 'sequel_secure_password'

gem 'dry-initializer'
gem 'dry-validation'

gem 'fast_jsonapi'

gem 'jwt'

group :development do
  gem 'byebug'
end

group :test do
  gem 'rspec'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'database_cleaner-sequel'
  gem 'byebug'
end
