# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.2'

gem 'rake'
gem 'bunny'
gem 'ougai'
gem 'amazing_print'

gem 'i18n'
gem 'config'
gem 'csv'

gem 'dry-initializer'
gem 'dry-validation'

gem 'faraday'
gem 'faraday_middleware'

group :development do
  gem 'byebug'
end

group :test do
  gem 'rspec'
  gem 'factory_bot'
  gem 'byebug'
end
