# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.2'

gem 'rake'
gem 'puma'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'faraday'
gem 'faraday_middleware'
gem 'rack-ougai'
gem 'rack-request-id'
gem 'amazing_print'

gem 'i18n'
gem 'config'

gem 'pg'
gem 'sequel'
gem 'bunny'

gem 'dry-initializer'
gem 'dry-validation'

gem 'fast_jsonapi'

group :development do
  gem 'byebug'
end

group :test do
  gem 'rspec'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'database_cleaner-sequel'
  gem 'byebug'
end
